apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgres-pv
  namespace: libreria-system
  labels:
    type: local
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: manual
  local:
    path: "/data/postgres"
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: tier
          operator: In
          values:
          - database
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-pvc
  namespace: libreria-system
  labels:
    app: postgres
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: manual
  resources:
    requests:
      storage: 5Gi