# Generated by Django 5.1.4 on 2025-04-22 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requests', '0002_alter_bookrequest_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookrequest',
            name='return_date',
        ),
        migrations.AddField(
            model_name='bookrequest',
            name='days_requested',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
