# Generated by Django 5.1.4 on 2025-01-14 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookrequest',
            name='copies_requested',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bookrequest',
            name='request_type',
            field=models.CharField(choices=[('loan', 'Loan'), ('copies', 'Request for more copies')], default='loan', max_length=100),
        ),
        migrations.AlterField(
            model_name='bookrequest',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='Pending', max_length=100),
        ),
    ]
