# Generated by Django 5.1.4 on 2025-01-16 02:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_bookrequest_copies_requested_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BookRequest',
        ),
    ]
